# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 90446484a16cbfbddcd38cf519de1dc94baccb1a822681a2a3485e347746e9fa24dfdd06721b7d5a4f1b2c14e0c66f991333b84283a8fe463a8ca03d959d6376

test:
  secret_key_base: 87c97678a0e52114b5631459bf6744d56cb7e6038373c701444efa6dd35ecf14f081a753c756fc5a69f85ae007752ad68e40fd92cf6ec4a09138bdf33889d009

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
